name: Build or Deploy Simplyblock Documentation
on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - '!main'

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: "documentation"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-test:
    if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Prepare Documentation Builder"
        run: |
          ./doc-builder build-image
      - name: "Build Documentation Test"
        run: |
          ./doc-builder build
  dev-deployment:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'
      - name: "Prepare Documentation Builder"
        run: |
          ./doc-builder build-image
      - name: "Prepare Documentation Dev Deployment"
        run: |
          ./doc-builder build
      - name: "Upload Documentation"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /dev/
          local-dir: ./site/
  deployment:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'
      - name: "Prepare Documentation Builder"
        run: |
          ./doc-builder build-image
      - name: "Adjust Release Name: ${{ github.ref_name }}"
        env:
          name: "${{ github.ref_name }}"
        run: |
          echo "RELEASE_NAME=$(echo ${name} | sed -e 's/.*\///g')" >> $GITHUB_ENV
      - name: "Prepare Documentation Deployment: ${{ env.RELEASE_NAME }}"
        run: |
          ./doc-builder deploy ${{ env.RELEASE_NAME }}
      - name: "Create Version Tag: ${{ env.RELEASE_NAME }}"
        run: |
          git config --global --add safe.directory $PWD
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add deployment
          git commit -m "Auto-Build: ${RELEASE_NAME}"
          git tag ${RELEASE_NAME}
          git push --tags --all
      - name: "Upload Documentation"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /
          local-dir: ./deployment/
          exclude: |
            **/latest/**
            versions.json
      - name: "Updating Latest"
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.ssh_server }}
          port: ${{ secrets.ssh_port }}
          username: ${{ secrets.ssh_username }}
          key: ${{ secrets.ssh_key }}
          script: |
            cd domains/simplyblock.io/public_html/docs/
            rm latest
            ln -s "./${{ env.RELEASE_NAME }}" "./latest"
            [ -f ./versions.json ] && ln -s ./latest/versions.json ./versions.json
      - name: "Merge Tag to Main"
        uses: mtanzi/action-automerge@v1
        with:
          github_token: "${{ github.token }}"
          source: "refs/tags/${{ env.RELEASE_NAME }}"
          target: "main"
          webhook_url: ""
